server:
  port: 8080
spring:
  config:
    activate: { import: optional:ConfigServer, on-profile: dev }
  application:
    name: config-client
  cloud:
    config:
      fail-fast: true
      enabled: true
      discovery:
        enabled: true
        #service-id: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
